#!/usr/bin/env python
import sys
import os
from mdb import Database

server  = 'http://localhost:5984/'
name = 'mdb'

for path in sys.argv[1:]:
    db = Database(server, name)
    if os.path.isfile(path):
        db.record(path)
        break
    for (dirname, _, files) in os.walk(path):
        for f in files: db.record(os.path.join(dirname, f))
