#!/usr/bin/env python
import sys
from optparse import OptionParser

from mdb.watch import Watcher

parser = OptionParser()
parser.add_option("-s", "--server", dest="server",
                  default='http://localhost:5984/', metavar="URL",
                  help="The URL of the CouchDB server to which to connect.")
parser.add_option("-n", "--name", dest="name", default="mdb",
                  help="The name of the database into which to import the music information.")
(options, args) = parser.parse_args()

watcher = Watcher(server=options.server, name=options.name)
for path in sys.argv[1:]:
    watcher.watch(path)
watcher.start()
